[build]
  command = "npm run build:netlify"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[context.production]
  command = "npm run build:netlify"

[context.deploy-preview]
  command = "npm run build:netlify"

[context.branch-deploy]
  command = "npm run build:netlify"

[context.dev]
  command = "npm run build:dev"

[context.sit]
  command = "npm run build:sit"

[context.uat]
  command = "npm run build:uat"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
